title: Lucifer's Store 4 HACK Recipes
description: "My Blog is for Hacking things ..."
author:
  name: "Hellhound"
  email: ""
  url: "LuX.github.io"

baseurl: ""
google_analytics: G-VN9LC7D5VG
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Lucifer69"
year : "2021"
