title: X4Tricks Blog
description: "This bolg made for Hacking posts ..."
author:
  name: "X"
  email: ""
  url: "https://x4tricks.github.io/"

baseurl: /.
google_analytics: G-J0VTN7B8NS
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Lucifer69"
year : "2021"
